# Generated by Django 4.2.23 on 2025-06-28 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pld',
            old_name='location_description',
            new_name='accessibility_features',
        ),
        migrations.RemoveField(
            model_name='building',
            name='accessible_entrances',
        ),
        migrations.RemoveField(
            model_name='building',
            name='address',
        ),
        migrations.RemoveField(
            model_name='building',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='pld',
            name='code',
        ),
        migrations.AddField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pld',
            name='entrance_lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pld',
            name='entrance_lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pld',
            name='entrance_name',
            field=models.CharField(default='Main Entrance', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pld',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plds', to='api.building'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_type', models.CharField(choices=[('vision', 'Visually Impaired'), ('mobility', 'Mobility Impaired'), ('hearing', 'Hearing Impaired')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
